DROP TABLE IF EXISTS flower_sensor;
CREATE TABLE flower_sensor(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,humidity VARCHAR(10) NOT NULL);
